
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-webapp-tutorial-io-v1-nicejob
  failurePolicy: Fail
  name: mnicejob.kb.io
  rules:
  - apiGroups:
    - webapp.tutorial.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nicejobs
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-webapp-tutorial-io-v1-nicejob
  failurePolicy: Fail
  name: vnicejob.kb.io
  rules:
  - apiGroups:
    - webapp.tutorial.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nicejobs
  sideEffects: None
